version: '3.4'

services:
  ui:
    build:
      context: .
      target: dev

    # host:container
    ports:
      - 3333:3000
      - 3001:3001

    # mount current directory to /app in the container
    volumes:
      - .env:/app/.env
      - ./package.json:/app/package.json
      - ./src:/app/src/
      - ./public:/app/public/

    # commands to run when the container starts
    command: >
      bash -c "npm start"