version: '3'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.local

    # host:container
    ports:
      - 3333:3000
      - 3001:3001

    # mount current directory to /app in the container
    volumes:
      - .:/app

    # commands to run when the container starts
    command: >
      bash -c "ln -sfn ../node_modules ./node_modules &&
               npm start"