version: '3'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - nginx
    links:
      - nginx
    environment:
      - CI=true
      - CYPRESS_baseUrl=http://172.16.86.11:80
      - CYPRESS_videoRecording=false

    networks:
      app_net:
        ipv4_address: 172.16.86.10

    volumes:
      - .:/usr/src/ui
              
    command: >
      bash -c "cd usr/src/ui && 
               npm install --production && 
               npm run build &&
               cypress run"

  nginx:
    image: nginx:latest
    ports:
      - 4000:80
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      app_net:
        ipv4_address: 172.16.86.11

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.86.0/24
