version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4000:80

  ui:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/app
    command: >
      bash -c "npm run build"
