version: '3.4'

services:
  ui:
    build:
      context: .
      target: dev

    # host:container
    ports:
      - 3333:3000
      - 3001:3001

    # mount current directory to /app in the container
    volumes:
      - .:/app

    # commands to run when the container starts
    command: >
      bash -c "npm start"