version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    # Access the site at port 4000
    ports:
      - 4000:80

  build:
    image: node:8
    volumes:
      - .:/usr/src/ui
    command: >
      bash -c "cd usr/src/ui &&
               npm install &&
               npm run build"
