version: '3'

services:
  ui:
    image: node:8

    # host:container
    ports:
      - 3333:3000
      - 3001:3001

    # mount our current directory to the container
    volumes:
      - .:/usr/src/ui

    # commands to run when the container starts
    command: >
      bash -c "cd usr/src/ui &&
               npm install &&
               npm start"
