FROM node:8

# Provides cached layer for node_modules
# these are installed in the directory above the /app
# folder so node will automatically look for them
COPY package*.json /
RUN npm install

# Any commands start from this directory IN the container
WORKDIR /app
