version: '3'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - nginx
    links:
      - nginx
    environment:
      - CI=true
      - CYPRESS_baseUrl=http://172.16.86.11:80
      - CYPRESS_videoRecording=false
    networks:
      app_net:
        ipv4_address: 172.16.86.10
    volumes:
      - .:/app
    command: >
      bash -c "npm run build &&
               ../node_modules/.bin/cypress run"

  nginx:
    image: nginx:latest
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      app_net:
        ipv4_address: 172.16.86.11
    logging:
      driver: none

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.86.0/24
