FROM cypress/base:8

# Provide a cached layer for node_modules
COPY package*.json /
RUN npm install
RUN $(npm bin)/cypress install
RUN $(npm bin)/cypress verify

# Any commands start from this directory IN the container
WORKDIR /app
