version: '3.4'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - nginx
    links:
      - nginx
    environment:
      - CI=true
      - CYPRESS_baseUrl=http://172.16.86.11:80
      - CYPRESS_videoRecording=false
    networks:
      app_net:
        ipv4_address: 172.16.86.10
    volumes:
      - ./cypress.json:/app/cypress.json
      - ./cypress:/app/cypress
    command: >
      bash -c "npx cypress run"

  nginx:
    build:
      context: .
      target: prod
    networks:
      app_net:
        ipv4_address: 172.16.86.11
    logging:
      driver: none

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.86.0/24
